SELECT 
    tc.CONSTRAINT_NAME,
    tc.CONSTRAINT_TYPE,
    c.COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE c
    ON tc.CONSTRAINT_NAME = c.CONSTRAINT_NAME
WHERE tc.TABLE_NAME = 'OrderItems'
  AND c.COLUMN_NAME = 'OrderItemKey';
